[project]
name = "root_gnomme"
version = "0.2.13"
authors = [
  { name="Jordan Langland", email="root@gnom.me" },
]
description = "hashwd is a command line tool that generates strong, random passwords using a list of words and optional numbers and symbols."
readme = "README.md"
requires-python = ">=3.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/astralsu/hashwd"
"Bug Tracker" = "https://github.com/astralsu/hashwd/issues"